# Generated by Django 5.2.8 on 2025-11-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_email_profile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='bullet_points',
            field=models.TextField(help_text='Enter bullet points separated by a newline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
