# Generated by Django 5.2.8 on 2025-11-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_slug_alter_project_bullet_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bullet_points',
            field=models.TextField(blank=True, help_text='Add bullet points separated by line breaks'),
        ),
        migrations.AlterField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills_used',
            field=models.ManyToManyField(blank=True, to='portfolio.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
