# Generated by Django 5.2.8 on 2025-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certification_education_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
